---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "default"
spec:
  configuration:
    users:
      default/password: ""
    clusters:
      - name: "db"
        layout:
          shardsCount: 1
          replicasCount: 1
