---
apiVersion: v1
kind: Service
metadata:
  name: agent
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/part-of: statshouse
spec:
  selector:
    app.kubernetes.io/name: agent
    app.kubernetes.io/part-of: statshouse
  ports:
    - port: 13337
      name: rpc
      protocol: TCP
    - port: 13337
      name: rpc-udp
      protocol: UDP
    - port: 13338
      name: api
      protocol: TCP