---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: statshouse
spec:
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: statshouse
  ports:
    - port: 10888
      name: api
      protocol: TCP