---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  labels:
    app.kubernetes.io/name: aggregator
    app.kubernetes.io/part-of: statshouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aggregator
      app.kubernetes.io/part-of: statshouse
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aggregator
        app.kubernetes.io/part-of: statshouse
    spec:
      volumes:
        - name: cache
          emptyDir: {}
      containers:
        - name: service
          image: ghcr.io/go-faster/statshouse:latest
          args:
            - aggregator
            - -u=root
            - -g=root
            - --cluster=test_shard_aggregator
            - --log-level=trace
            - --agg-addr=':13336'
            - --kh=kh:8123
            - --metadata-addr=metadata:2442
            - --auto-create
            - --cache-dir=/var/lib/statshouse/cache/aggregator
          ports:
            - containerPort: 13336
              protocol: TCP
              name: api
          volumeMounts:
            - mountPath: /var/lib/statshouse/cache/
              name: cache
